<?php

return [
    'categories' => [
        ['id' => 'all', 'name' => 'Semua Kategori', 'icon' => null],
        ['id' => 'best-seller', 'name' => 'Best Seller', 'icon' => 'star'],
        ['id' => 'safety', 'name' => 'Alat Pelindung Kerja (APD)', 'icon' => 'shield-alert'],
        ['id' => 'atk', 'name' => 'Alat Tulis Kantor', 'icon' => 'pen-tool'],
        ['id' => 'kebersihan', 'name' => 'Alat Kebersihan', 'icon' => 'spray-can'],
    ],

    'items' => [
        // ================= SAFETY / APD =================
        [
            'id' => 'helm-safety',
            'category' => 'safety',
            'name' => 'Helm Safety (Proyek)',
            'desc' => 'Helm pelindung kepala standar SNI untuk keselamatan kerja di proyek dan industri.',
            'min_order' => '10 Pcs',
            'features' => ['Standar SNI & ANSI', 'Bahan HDPE berkualitas', 'Tersedia berbagai warna (Kuning, Putih, Merah, dll)'],
            'image' => 'https://loremflickr.com/600/400/hard,hat/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'rompi-safety',
            'category' => 'safety',
            'name' => 'Rompi Safety (Safety Vest)',
            'desc' => 'Rompi proyek high-visibility dengan pita reflektif untuk keamanan kerja siang dan malam.',
            'min_order' => '1 Lusin (12 Pcs)',
            'features' => ['Pita reflektif terang', 'Bahan jaring/polyester nyaman', 'Tersedia ukuran all-size'],
            'image' => 'https://loremflickr.com/600/400/safety,vest/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'sepatu-safety',
            'category' => 'safety',
            'name' => 'Sepatu Safety (Steel Toe)',
            'desc' => 'Sepatu keselamatan kerja dengan ujung besi (steel toe cap) pelindung benturan dan anti-slip.',
            'min_order' => '5 Pasang',
            'features' => ['Ujung pelindung besi tahan tekanan', 'Sol karet anti-slip & tahan minyak', 'Desain tangguh untuk lapangan'],
            'image' => 'https://loremflickr.com/600/400/safety,boots/all',
            'is_best_seller' => true,
        ],
        [
            'id' => 'kacamata-safety',
            'category' => 'safety',
            'name' => 'Kacamata Safety (Safety Goggles)',
            'desc' => 'Kacamata pelindung untuk melindungi mata dari debu, percikan material, dan sinar UV.',
            'min_order' => '2 Lusin (24 Pcs)',
            'features' => ['Lensa polycarbonate anti-gores', 'Desain ergonomis & nyaman', 'Tersedia lensa bening & gelap'],
            'image' => 'https://loremflickr.com/600/400/safety,glasses/all',
            'is_best_seller' => true,
        ],
        [
            'id' => 'masker-respirator',
            'category' => 'safety',
            'name' => 'Masker Respirator',
            'desc' => 'Masker filter pernapasan untuk melindungi dari debu, gas, dan partikel berbahaya.',
            'min_order' => '10 Pcs',
            'features' => ['Filter cartridge yang dapat diganti', 'Katup pernapasan ganda', 'Silikon lembut pas di wajah'],
            'image' => 'https://loremflickr.com/600/400/respirator,mask/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'sarung-tangan-kerja',
            'category' => 'safety',
            'name' => 'Sarung Tangan Kerja',
            'desc' => 'Berbagai jenis sarung tangan untuk proyek, industri, dan pekerjaan kasar.',
            'min_order' => '5 Lusin',
            'features' => ['Sarung tangan katun / bintik', 'Sarung tangan kulit heavy duty', 'Sarung tangan karet anti bahan kimia'],
            'image' => 'https://loremflickr.com/600/400/work,gloves/all',
            'is_best_seller' => true,
        ],
        
        // Alat Penunjang Kerja (gabung ke safety untuk sementera atau kategori sendiri, tapi best seller items)
        [
            'id' => 'hand-tools-set',
            'category' => 'safety', 
            'name' => 'Palu & Obeng Set (Hand Tools)',
            'desc' => 'Set peralatan perkakas tangan esensial untuk kebutuhan pemeliharaan dan perbaikan.',
            'min_order' => '2 Set',
            'features' => ['Bahan material berkualitas', 'Grip anti-slip', 'Dilengkapi kotak penyimpanan'],
            'image' => 'https://loremflickr.com/600/400/hand,tools/all',
            'is_best_seller' => true,
        ],
        [
            'id' => 'pallet-plastik',
            'category' => 'safety',
            'name' => 'Pallet Plastik',
            'desc' => 'Pallet berbahan plastik HDPE yang kuat, tahan lama, dan anti-rayap untuk kebutuhan gudang dan logistik.',
            'min_order' => '10 Pcs',
            'features' => ['Kapasitas beban statis/dinamis tinggi', 'Mudah dibersihkan', 'Cocok untuk forklift & hand pallet'],
            'image' => 'https://loremflickr.com/600/400/plastic,pallet/all',
            'is_best_seller' => true,
        ],
        [
            'id' => 'stretch-film',
            'category' => 'safety',
            'name' => 'Stretch Film / Wrapping Plastic',
            'desc' => 'Plastik wrapping fleksibel untuk membungkus barang atau palet agar stabil dan aman dari debu/air.',
            'min_order' => '1 Dus (6 Roll)',
            'features' => ['Daya rekat dan regang kuat', 'Tersedia berbagai ketebalan (mikron)', 'Melindungi barang saat pengiriman'],
            'image' => 'https://loremflickr.com/600/400/stretch,film,packaging/all',
            'is_best_seller' => true,
        ],
        [
            'id' => 'lakban-isolasi',
            'category' => 'atk', 
            'name' => 'Lakban & Isolasi (Tape)',
            'desc' => 'Lakban kemasan, lakban kain, isolasi bening/coklat, dan masking tape berbagai ukuran.',
            'min_order' => '1 Dus (72 Roll)',
            'features' => ['Daya rekat ekstra kuat', 'Tidak mudah putus', 'Tersedia untuk pengemasan berat (Heavy Duty)'],
            'image' => 'https://loremflickr.com/600/400/duct,tape/all',
            'is_best_seller' => true,
        ],
        [
            'id' => 'kertas-amplas',
            'category' => 'safety',
            'name' => 'Kertas Amplas',
            'desc' => 'Kertas amplas untuk menghaluskan permukaan kayu, besi, maupun pengerjaan industri.',
            'min_order' => '50 Lembar / 1 Roll',
            'features' => ['Berbagai tingkat kekasaran (Grit)', 'Tahan air (Waterproof opsi)', 'Tahan aus untuk pemakaian lama'],
            'image' => 'https://loremflickr.com/600/400/sandpaper/all',
            'is_best_seller' => true,
        ],

        // ================= ATK =================
        [
            'id' => 'buku-map-ordner',
            'category' => 'atk',
            'name' => 'Buku, Map & Ordner',
            'desc' => 'Kebutuhan pengarsipan dan pencatatan kantor: buku tulis, map plastik, ordner dokumen.',
            'min_order' => '1 Lusin',
            'features' => ['Kualitas kertas standar ISO', 'Ordner kokoh untuk arsip tebal', 'Tersedia berbagai ukuran (A4, F4)'],
            'image' => 'https://loremflickr.com/600/400/office,binders/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'kertas-hvs',
            'category' => 'atk',
            'name' => 'Kertas HVS & Amplop',
            'desc' => 'Kertas fotokopi, kertas print (70gsm/80gsm) ukuran A4/F4, dan berbagai ukuran amplop surat.',
            'min_order' => '1 Dus (5 Rim)',
            'features' => ['Putih bersih & tidak mudah macet', 'Gramatur presisi', 'Amplop dengan seal perekat'],
            'image' => 'https://loremflickr.com/600/400/copy,paper/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'alat-tulis',
            'category' => 'atk',
            'name' => 'Pena, Pensil & Spidol',
            'desc' => 'Peralatan tulis harian untuk kantor dan industri. Pena gel, spidol permanen, pensil kayu/mekanik.',
            'min_order' => '10 Pack',
            'features' => ['Tinta lancar & cepat kering', 'Merek terpercaya (Snowman, Kenko, dll)', 'Spidol whiteboard/permanen'],
            'image' => 'https://loremflickr.com/600/400/pens,pencils/all',
            'is_best_seller' => false,
        ],

        // ================= ALAT KEBERSIHAN =================
        [
            'id' => 'mop-pel-lantai',
            'category' => 'kebersihan',
            'name' => 'Mop & Pel Lantai',
            'desc' => 'Kain pel, alat pel dengan gagang, dan lobo mop untuk kebersihan lantai area luas.',
            'min_order' => '5 Set',
            'features' => ['Daya serap air tinggi', 'Gagang kokoh (alumunium/kayu)', 'Refill kain pel mudah diganti'],
            'image' => 'https://loremflickr.com/600/400/mop,floor/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'ember-pel',
            'category' => 'kebersihan',
            'name' => 'Ember Pel (Mop Bucket)',
            'desc' => 'Ember pemerasan kain pel (wringer bucket) kapasitas besar dengan roda penggerak.',
            'min_order' => '2 Unit',
            'features' => ['Kapasitas 20L - 36L', 'Pemeras tuas yang efisien', 'Bahan plastik industri awet'],
            'image' => 'https://loremflickr.com/600/400/cleaning,bucket/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'kantong-sampah',
            'category' => 'kebersihan',
            'name' => 'Kantong Sampah (Trash Bag)',
            'desc' => 'Kantong plastik sampah hitam (Polybag) berbagai ukuran untuk kebutuhan domestik dan medis.',
            'min_order' => '50 Pack',
            'features' => ['Bahan tebal tidak mudah sobek', 'Tersedia ukuran 40x60 hingga 120x150 cm', 'Ramah lingkungan (opsional)'],
            'image' => 'https://loremflickr.com/600/400/trash,bags/all',
            'is_best_seller' => true,
        ],
        [
            'id' => 'vacuum-cleaner',
            'category' => 'kebersihan',
            'name' => 'Mesin Vacuum Cleaner',
            'desc' => 'Penyedot debu basah & kering (Wet & Dry Vacuum) untuk perkantoran dan industri.',
            'min_order' => '1 Unit',
            'features' => ['Daya hisap kuat', 'Kapasitas tangki besar', 'Bisa untuk air dan debu kering'],
            'image' => 'https://loremflickr.com/600/400/vacuum,cleaner/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'sikat-toilet',
            'category' => 'kebersihan',
            'name' => 'Alat Kebersihan Toilet',
            'desc' => 'Sikat kloset, cairan pembersih, pengharum ruangan, dan kapur barus.',
            'min_order' => '5 Set',
            'features' => ['Membersihkan noda membandel', 'Menghilangkan bau tidak sedap', 'Sikat berdesain melengkung'],
            'image' => 'https://loremflickr.com/600/400/toilet,brush/all',
            'is_best_seller' => false,
        ],
        [
            'id' => 'wet-floor-sign',
            'category' => 'kebersihan',
            'name' => 'Wet Floor Sign',
            'desc' => 'Papan peringatan lantai basah (Caution Wet Floor) untuk keselamatan area publik.',
            'min_order' => '5 Pcs',
            'features' => ['Warna kuning terang mencolok', 'Desain lipat mudah disimpan', 'Tulisan peringatan bilingual'],
            'image' => 'https://loremflickr.com/600/400/wet,floor,sign/all',
            'is_best_seller' => false,
        ],
    ]
];
