<?php

return [
    'categories' => [
        ['id' => 'all', 'name' => 'Semua Kategori', 'icon' => null],
        ['id' => 'best-seller', 'name' => 'Best Seller', 'icon' => 'star'],
        ['id' => 'safety', 'name' => 'Alat Pelindung Kerja (APD)', 'icon' => 'shield-alert'],
        ['id' => 'atk', 'name' => 'Alat Tulis Kantor', 'icon' => 'pen-tool'],
        ['id' => 'kebersihan', 'name' => 'Alat Kebersihan', 'icon' => 'spray-can'],
    ],

    'items' => [
        // ================= SAFETY / APD =================
        [
            'id' => 'helm-safety',
            'category' => 'safety',
            'name' => 'Helm Safety (Proyek)',
            'desc' => 'Helm pelindung kepala standar SNI untuk keselamatan kerja di proyek dan industri.',
            'min_order' => '10 Pcs',
            'features' => ['Standar SNI & ANSI', 'Bahan HDPE berkualitas', 'Tersedia berbagai warna (Kuning, Putih, Merah, dll)'],
            'image' => 'https://image.ska-safety.com/s3/productimages/webp/co1285/p542366/w600-h600/392fb696-24cf-4d3a-86c0-9e8ac3838d34w.png',
            'is_best_seller' => false,
        ],
        [
            'id' => 'rompi-safety',
            'category' => 'safety',
            'name' => 'Rompi Safety (Safety Vest)',
            'desc' => 'Rompi proyek high-visibility dengan pita reflektif untuk keamanan kerja siang dan malam.',
            'min_order' => '1 Lusin (12 Pcs)',
            'features' => ['Pita reflektif terang', 'Bahan jaring/polyester nyaman', 'Tersedia ukuran all-size'],
            'image' => 'https://image.ska-safety.com/s3/productimages/webp/co1285/p548100/w600-h600/704de808-0764-44e2-b813-29d357c1cce4w.jpg',
            'is_best_seller' => false,
        ],
        [
            'id' => 'sepatu-safety',
            'category' => 'safety',
            'name' => 'Sepatu Safety (Steel Toe)',
            'desc' => 'Sepatu keselamatan kerja dengan ujung besi (steel toe cap) pelindung benturan dan anti-slip.',
            'min_order' => '5 Pasang',
            'features' => ['Ujung pelindung besi tahan tekanan', 'Sol karet anti-slip & tahan minyak', 'Desain tangguh untuk lapangan'],
            'image' => 'https://image.ska-safety.com/s3/productimages/webp/co1285/p1551900/w600-h600/1751fb03-8a3c-49a9-b1d6-da2ccceb43f4.png',
            'is_best_seller' => true,
        ],
        [
            'id' => 'kacamata-safety',
            'category' => 'safety',
            'name' => 'Kacamata Safety (Safety Goggles)',
            'desc' => 'Kacamata pelindung untuk melindungi mata dari debu, percikan material, dan sinar UV.',
            'min_order' => '2 Lusin (24 Pcs)',
            'features' => ['Lensa polycarbonate anti-gores', 'Desain ergonomis & nyaman', 'Tersedia lensa bening & gelap'],
            'image' => 'https://image.ska-safety.com/s3/productimages/webp/co1285/p1521882/w600-h600/8f22b22e-c654-4c52-be9c-5243612bbd4c.png',
            'is_best_seller' => true,
        ],
        [
            'id' => 'masker-respirator',
            'category' => 'safety',
            'name' => 'Masker Respirator',
            'desc' => 'Masker filter pernapasan untuk melindungi dari debu, gas, dan partikel berbahaya.',
            'min_order' => '10 Pcs',
            'features' => ['Filter cartridge yang dapat diganti', 'Katup pernapasan ganda', 'Silikon lembut pas di wajah'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/4/48/SH9550-Cropped.jpg',
            'is_best_seller' => false,
        ],
        [
            'id' => 'sarung-tangan-kerja',
            'category' => 'safety',
            'name' => 'Sarung Tangan Kerja',
            'desc' => 'Berbagai jenis sarung tangan untuk proyek, industri, dan pekerjaan kasar.',
            'min_order' => '5 Lusin',
            'features' => ['Sarung tangan katun / bintik', 'Sarung tangan kulit heavy duty', 'Sarung tangan karet anti bahan kimia'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/0/01/Centre_de_Documentaci%C3%B3_Museu_T%C3%A8xtil_de_Terrassa-_Reserves-_Teixits-_Guants002.JPG',
            'is_best_seller' => true,
        ],
        
        // Alat Penunjang Kerja
        [
            'id' => 'hand-tools-set',
            'category' => 'safety', 
            'name' => 'Palu & Obeng Set (Hand Tools)',
            'desc' => 'Set peralatan perkakas tangan esensial untuk kebutuhan pemeliharaan dan perbaikan.',
            'min_order' => '2 Set',
            'features' => ['Bahan material berkualitas', 'Grip anti-slip', 'Dilengkapi kotak penyimpanan'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Glardon_Vallorbe_LA2442-0_140_mm_Swiss_cut_0_6-piece_needle_file_set.png',
            'is_best_seller' => true,
        ],
        [
            'id' => 'pallet-plastik',
            'category' => 'safety',
            'name' => 'Pallet Plastik',
            'desc' => 'Pallet berbahan plastik HDPE yang kuat, tahan lama, dan anti-rayap untuk kebutuhan gudang dan logistik.',
            'min_order' => '10 Pcs',
            'features' => ['Kapasitas beban statis/dinamis tinggi', 'Mudah dibersihkan', 'Cocok untuk forklift & hand pallet'],
            'image' => 'https://m.media-amazon.com/images/I/61X-uF7aR9L._AC_SL1500_.jpg',
            'is_best_seller' => true,
        ],
        [
            'id' => 'stretch-film',
            'category' => 'safety',
            'name' => 'Stretch Film / Wrapping Plastic',
            'desc' => 'Plastik wrapping fleksibel untuk membungkus barang atau palet agar stabil dan aman dari debu/air.',
            'min_order' => '1 Dus (6 Roll)',
            'features' => ['Daya rekat dan regang kuat', 'Tersedia berbagai ketebalan (mikron)', 'Melindungi barang saat pengiriman'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Pallet_wrapper.jpg',
            'is_best_seller' => true,
        ],
        [
            'id' => 'lakban-isolasi',
            'category' => 'atk', 
            'name' => 'Lakban & Isolasi (Tape)',
            'desc' => 'Lakban kemasan, lakban kain, isolasi bening/coklat, dan masking tape berbagai ukuran.',
            'min_order' => '1 Dus (72 Roll)',
            'features' => ['Daya rekat ekstra kuat', 'Tidak mudah putus', 'Tersedia untuk pengemasan berat (Heavy Duty)'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/8/89/Duct-tape.jpg',
            'is_best_seller' => true,
        ],
        [
            'id' => 'kertas-amplas',
            'category' => 'safety',
            'name' => 'Kertas Amplas',
            'desc' => 'Kertas amplas untuk menghaluskan permukaan kayu, besi, maupun pengerjaan industri.',
            'min_order' => '50 Lembar / 1 Roll',
            'features' => ['Berbagai tingkat kekasaran (Grit)', 'Tahan air (Waterproof opsi)', 'Tahan aus untuk pemakaian lama'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/9/90/Schleifpapier_verschiedene_Sorten.jpg',
            'is_best_seller' => true,
        ],

        // ================= ATK =================
        [
            'id' => 'buku-map-ordner',
            'category' => 'atk',
            'name' => 'Buku, Map & Ordner',
            'desc' => 'Kebutuhan pengarsipan dan pencatatan kantor: buku tulis, map plastik, ordner dokumen.',
            'min_order' => '1 Lusin',
            'features' => ['Kualitas kertas standar ISO', 'Ordner kokoh untuk arsip tebal', 'Tersedia berbagai ukuran (A4, F4)'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Lever_arch_file.jpg',
            'is_best_seller' => false,
        ],
        [
            'id' => 'kertas-hvs',
            'category' => 'atk',
            'name' => 'Kertas HVS & Amplop',
            'desc' => 'Kertas fotokopi, kertas print (70gsm/80gsm) ukuran A4/F4, dan berbagai ukuran amplop surat.',
            'min_order' => '1 Dus (5 Rim)',
            'features' => ['Putih bersih & tidak mudah macet', 'Gramatur presisi', 'Amplop dengan seal perekat'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/2/25/Various_products_made_from_paper.JPG',
            'is_best_seller' => false,
        ],
        [
            'id' => 'alat-tulis',
            'category' => 'atk',
            'name' => 'Pena, Pensil & Spidol',
            'desc' => 'Peralatan tulis harian untuk kantor dan industri. Pena gel, spidol permanen, pensil kayu/mekanik.',
            'min_order' => '10 Pack',
            'features' => ['Tinta lancar & cepat kering', 'Merek terpercaya (Snowman, Kenko, dll)', 'Spidol whiteboard/permanen'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/e/e1/03-BICcristal2008-03-26.jpg',
            'is_best_seller' => false,
        ],

        // ================= ALAT KEBERSIHAN =================
        [
            'id' => 'mop-pel-lantai',
            'category' => 'kebersihan',
            'name' => 'Mop & Pel Lantai',
            'desc' => 'Kain pel, alat pel dengan gagang, dan lobo mop untuk kebersihan lantai area luas.',
            'min_order' => '5 Set',
            'features' => ['Daya serap air tinggi', 'Gagang kokoh (alumunium/kayu)', 'Refill kain pel mudah diganti'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Mop%2C_three_different_mop_handles.jpg',
            'is_best_seller' => false,
        ],
        [
            'id' => 'ember-pel',
            'category' => 'kebersihan',
            'name' => 'Ember Pel (Mop Bucket)',
            'desc' => 'Ember pemerasan kain pel (wringer bucket) kapasitas besar dengan roda penggerak.',
            'min_order' => '2 Unit',
            'features' => ['Kapasitas 20L - 36L', 'Pemeras tuas yang efisien', 'Bahan plastik industri awet'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Gotland-Bottarve_Museumshof_07.jpg',
            'is_best_seller' => false,
        ],
        [
            'id' => 'kantong-sampah',
            'category' => 'kebersihan',
            'name' => 'Kantong Sampah (Trash Bag)',
            'desc' => 'Kantong plastik sampah hitam (Polybag) berbagai ukuran untuk kebutuhan domestik dan medis.',
            'min_order' => '50 Pack',
            'features' => ['Bahan tebal tidak mudah sobek', 'Tersedia ukuran 40x60 hingga 120x150 cm', 'Ramah lingkungan (opsional)'],
            'image' => 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Trash_bin_in_Paris.jpg',
            'is_best_seller' => true,
        ],
        [
            'id' => 'vacuum-cleaner',
            'category' => 'kebersihan',
            'name' => 'Mesin Vacuum Cleaner',
            'desc' => 'Penyedot debu basah & kering (Wet & Dry Vacuum) untuk perkantoran dan industri.',
            'min_order' => '1 Unit',
            'features' => ['Daya hisap kuat', 'Kapasitas tangki besar', 'Bisa untuk air dan debu kering'],
            'image' => 'https://m.media-amazon.com/images/I/71u9sWnI0KL._AC_SL1500_.jpg',
            'is_best_seller' => false,
        ],
        [
            'id' => 'sikat-toilet',
            'category' => 'kebersihan',
            'name' => 'Alat Kebersihan Toilet',
            'desc' => 'Sikat kloset, cairan pembersih, pengharum ruangan, dan kapur barus.',
            'min_order' => '5 Set',
            'features' => ['Membersihkan noda membandel', 'Menghilangkan bau tidak sedap', 'Sikat berdesain melengkung'],
            'image' => 'https://m.media-amazon.com/images/I/71f-0eM+CPL._AC_SL1500_.jpg',
            'is_best_seller' => false,
        ],
        [
            'id' => 'wet-floor-sign',
            'category' => 'kebersihan',
            'name' => 'Wet Floor Sign',
            'desc' => 'Papan peringatan lantai basah (Caution Wet Floor) untuk keselamatan area publik.',
            'min_order' => '5 Pcs',
            'features' => ['Warna kuning terang mencolok', 'Desain lipat mudah disimpan', 'Tulisan peringatan bilingual'],
            'image' => 'https://m.media-amazon.com/images/I/71M27a00fTL._AC_SL1500_.jpg',
            'is_best_seller' => false,
        ],
    ]
];
